[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "autodonate"
description = "Бесплатный и модульный сайт авто-доната для майнкрафт серверов."
version = "0.1.0.alpha.0"
license = "AGPL3"

authors = [
  "PerchunPak <PerchunPak@users.noreply.github.com>",
  "cofob <cofob@riseup.net>"
]

readme = "README.md"

repository = "https://github.com/fire-squad/autodonate"

[tool.poetry.dependencies]
python = "^3.10"
poetry = "^1"
Django = "^4.0.2"
requests = "^2.27.1"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
mypy = "^0.931"

wemake-python-styleguide = "^0.16"
flake8-pytest-style = "^1.6"

safety = "^1.10"

pytest = "^7.0"
pytest-cov = "^3.0"
pytest-randomly = "^3.11"

sphinx = "^4.4"
sphinx-autodoc-typehints = "^1.17"
doc8 = "^0.10"
m2r2 = "^0.3"
tomlkit = "^0.10"
