name: Screenshot

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: |
        curl -sSL "https://install.python-poetry.org" | python

        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install -E screenshot-script

    - name: Install node
      uses: bahmutov/npm-install@v1
      with:
        working-directory: svelte

    - name: Build Svelte
      working-directory: svelte
      run: npm run build

    - name: Make and run migrations
      run: |
        poetry run python manage.py makemigrations --noinput
        poetry run python manage.py migrate

    - name: Run server and script
      run: |
        poetry run python manage.py runserver &
        sleep 5
        poetry run python .github/scripts/screenshot.py

    - name: Make arifacts
      uses: actions/upload-artifact@v3
      with:
        name: screen
        path: screenshot-*.png

    - name: Upload images
      run: |
        poetry run python .github/scripts/upload.py ${{ secrets.BIN_SECRET }} $(git rev-parse --short HEAD)
